// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrPLdoZYLtVNvKLxp9Y-w1gt6DU6XzNeY',
    appId: '1:186899771699:web:ba7ce7b9316f16a99cce46',
    messagingSenderId: '186899771699',
    projectId: 'chichii-online-a6af6',
    authDomain: 'chichii-online-a6af6.firebaseapp.com',
    storageBucket: 'chichii-online-a6af6.firebasestorage.app',
    measurementId: 'G-3QV7YSPHCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_jPqNdd0be753KceO7rpYbt5bX4dmXI4',
    appId: '1:186899771699:android:04c2ad0618da5d189cce46',
    messagingSenderId: '186899771699',
    projectId: 'chichii-online-a6af6',
    storageBucket: 'chichii-online-a6af6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCJenLi7H7kH8veai5WOmhi59_YMehbw0',
    appId: '1:186899771699:ios:7967074ac4f751499cce46',
    messagingSenderId: '186899771699',
    projectId: 'chichii-online-a6af6',
    storageBucket: 'chichii-online-a6af6.firebasestorage.app',
    iosBundleId: 'com.example.padshala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCJenLi7H7kH8veai5WOmhi59_YMehbw0',
    appId: '1:186899771699:ios:7967074ac4f751499cce46',
    messagingSenderId: '186899771699',
    projectId: 'chichii-online-a6af6',
    storageBucket: 'chichii-online-a6af6.firebasestorage.app',
    iosBundleId: 'com.example.padshala',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrPLdoZYLtVNvKLxp9Y-w1gt6DU6XzNeY',
    appId: '1:186899771699:web:87c27656ec8d75909cce46',
    messagingSenderId: '186899771699',
    projectId: 'chichii-online-a6af6',
    authDomain: 'chichii-online-a6af6.firebaseapp.com',
    storageBucket: 'chichii-online-a6af6.firebasestorage.app',
    measurementId: 'G-JD4SJNCDMK',
  );
}
